# Site settings
title: Tyler Morrow
email: tmorrow@mst.edu
description: ""
baseurl: ""
encoding: UTF-8

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

exclude:
  - s3_website.yml